// src/components/ExamplesBrowser.svelte
<script lang="ts">
    export let items: {
        data: {
            title: string;
            embed: string;
        };
        slug: string;
    }[];
    export let hasDetails = false;
    let active = 0;
    let setActive = (index: number) => {
        active = index;
    };
    import MultiQCIconSrc from "/logos/multiqc_logo_square.svg";
    import Button from "@components/Button.svelte";
</script>

<div class="overflow-hidden rounded-md border border-gray-200 shadow text-gray-800">
  <div class="overflow-hidden rounded-md border border-gray-200 shadow">
      {#if items.length === 1}
        <div class="flex border-b border-gray-200 bg-gray-100">
          <div class="flex px-4 pt-4 pb-2">
            <img
              src={MultiQCIconSrc}
              alt="MultiQC Logo"
              class="mr-2 h-6 w-6 my-0"
            />
            <span class="typo-small -mt-0.5">
              Example Report: {items[0].data.title}
            </span>
          </div>
        </div>
      {:else}
        <div class="flex border-b border-gray-200 bg-gray-100">
          <div class="flex px-4 pt-4 pb-2 lg:w-[250px]">
            <img
              src={MultiQCIconSrc}
              alt="MultiQC Logo"
              class="mr-2 h-6 w-6"
            />
            <span class="typo-small -mt-0.5 ">Example Reports</span>
          </div>
          <div class="flex pt-2">
            {#each items as item,index (index) }
              
              <div id={`example-report-btn-${item.data.title}`}>
                <button
                  class={
                    "typo-small bg-gray-2 h-full rounded-t-sm px-4 "+
                    (index !== active ? "hover:bg-white": "bg-gray-200 hover:bg-gray-200"
                    )
                  }
                  on:click={() => {
                    setActive(index);
                  }}
                >
                  {item.data.title}
                </button>
              </div>
            
            {/each}
          </div>
          {#if hasDetails}
            <div class="grow py-2 px-4 text-right">
              <Button to={"/example-reports/"+items[active].slug} variant="secondary" size="sm">
                See report details
              </Button>
            </div>
          {/if}
        </div>
      {/if}
      <div>
        <iframe
          src={items[active].data.embed}
          title="Example Report"
          class="h-[600px] w-full"
        />
      </div>
    </div>
</div>

// src/components/ExamplesBrowser/index.jsx
import classnames from "classnames";
import React, { useState } from "react";

import { Button } from "website-components";

import MultiQCIconSrc from "../../images/icons/multiqc.svg";

const ExamplesBrowser = ({ items, hasDetails }) => {
  const [active, setActive] = useState(0);

  return (
    <div className="overflow-hidden rounded-md border border-gray-200 shadow">
      {items.length === 1 && (
        <div className="flex border-b border-gray-200 bg-gray-100">
          <div className="flex px-4 pt-4 pb-2">
            <img
              src={MultiQCIconSrc}
              alt="MultiQC Logo"
              className="mr-2 h-6 w-6"
            />
            <span className="typo-small -mt-0.5">
              Example Report: {items[0].title}
            </span>
          </div>
        </div>
      )}
      {items.length > 1 && (
        <div className="flex border-b border-gray-200 bg-gray-100">
          <div className="flex px-4 pt-4 pb-2 lg:w-[250px]">
            <img
              src={MultiQCIconSrc}
              alt="MultiQC Logo"
              className="mr-2 h-6 w-6"
            />
            <span className="typo-small -mt-0.5">Example Reports</span>
          </div>
          <div className="flex pt-2">
            {items.map((item, index) => (
              <div key={`example-report-btn-${item.title}`}>
                <button
                  className={classnames(
                    "typo-small bg-gray-2 h-full rounded-t-sm px-4",
                    {
                      "hover:bg-white": index !== active,
                      "bg-gray-200 hover:bg-gray-200": index === active,
                    }
                  )}
                  onClick={() => {
                    setActive(index);
                  }}
                >
                  {item.title}
                </button>
              </div>
            ))}
          </div>
          {hasDetails && (
            <div className="grow py-2 px-4 text-right">
              <Button to={items[active].path} variant="secondary" size="sm">
                See report details
              </Button>
            </div>
          )}
        </div>
      )}
      <div>
        <iframe
          src={items[active].embed}
          title="Example Report"
          className="h-[600px] w-full"
        />
      </div>
    </div>
  );
};

export default ExamplesBrowser;
